name: Auto Login
 
on:
  push:
    branches: [ main ]
 
jobs:
  auto-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
 
      - name: Auto Login to Service
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "$USERNAME"
          echo "$PASSWORD"
          # 在这里添加你的自动登录脚本或命令